package com.mikewerzen.automation.assistant.core.nlp.container.syntax

enum class Aspect
{ ASPECT_UNKNOWN, PERFECTIVE, IMPERFECTIVE, PROGRESSIVE }

enum class Case
{ CASE_UNKNOWN, ACCUSATIVE, ADVERBIAL, COMPLEMENTIVE, DATIVE, GENITIVE, INSTRUMENTAL, LOCATIVE, NOMINATIVE, OBLIQUE, PARTITIVE, PREPOSITIONAL, REFLEXIVE_CASE, RELATIVE_CASE, VOCATIVE }

enum class Form
{ FORM_UNKNOWN, ADNOMIAL, AUXILIARY, COMPLEMENTIZER, FINAL_ENDING, GERUND, REALIS, IRREALIS, SHORT, LONG, ORDER, SPECIFIC }

enum class Gender
{ GENDER_UNKNOWN, FEMININE, MASCULINE, NEUTER }

enum class Mood
{MOOD_UNKNOWN, CONDITIONAL_MOOD, IMPERATIVE, INDICATIVE, INTERROGATIVE, JUSSIVE, SUBJUNCTIVE }

enum class Number
{NUMBER_UNKNOWN, SINGULAR, PLURAL, DUAL }

enum class Person
{ PERSON_UNKNOWN, FIRST, SECOND, THIRD, REFLEXIVE_PERSON }

enum class Proper
{PROPER_UNKNOWN, PROPER, NOT_PROPER }

enum class Reciprocity
{ RECIPROCITY_UNKNOWN, RECIPROCAL, NON_RECIPROCAL }

enum class Tense
{TENSE_UNKNOWN, CONDITIONAL_TENSE, FUTURE, PAST, PRESENT, IMPERFECT, PLUPERFECT }

enum class Voice
{VOICE_UNKNOWN, ACTIVE, CAUSATIVE, PASSIVE }