#!/bin/bash
# Assistant
#
# description: Assistant Core

case $1 in
    start)
        nohup java -jar /assistant/core/assistant.jar >> /tmp/core.out 2>&1&
    ;;
    stop)
        /bin/bash pkill *assistant*.jar
    ;;
esac
exit 0
